version: "3.4"

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_PASSWORD=api
      - POSTGRES_USER=api
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
